# Generated by Django 4.2.3 on 2023-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='teniss',
            new_name='tenis',
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
