# Generated by Django 4.2.3 on 2023-07-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='imagem',
            field=models.ImageField(upload_to='tenis'),
        ),
    ]
