# Generated by Django 4.2.3 on 2023-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_tenis_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='imagem',
            field=models.ImageField(upload_to='tenisimg/'),
        ),
    ]
