# Generated by Django 4.2.3 on 2023-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_alter_tenis_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
